### ISSUE TITLE
améliorer le rendu des résultats de recherche

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#1]

**Comment by Shuunen** [comment]
@bengrol j'aimerai bien m'en occuper mais je vois pas trop à quoi ça doit ressembler au final ? un exemple sur un site ?

**Comment by bengrol** [comment]
J’ai pas trop d’idée - je suis sûr que tu vas trouver un truc chouette.

**Comment by Shuunen** [comment]
@bengrol ça n'a plus d'intérêt non ? on clôture ?
