### ISSUE TITLE
transformer les pages domaines

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#13]
A date, les pages "domaines" présentent un château (POI) ou on vend du vin.
Il faut modifier cela pour présenter les différents domaine de la région : 
- Pecharmant 
- Montravel
- Saussignac
- etc
Le contenu pourrait être stocké de la même façon. JsonBD.

**Comment by LeGaby** [comment]
@Shuunen j'allais me lancer dans la création des pages de présentation des domaines. Je comptais faire un composant générique mais peut-être que c'est le rôle de pages/domaine/_id.vue ?

**Comment by Shuunen** [comment]
`pages/domaine/_id.vue` c'est la page de détails d'un domaine/chateau

@bengrol quand tu dis "Il faut modifier cela pour présenter les différents domaine de la région" tu sous entends qu'il n'y a plus de page domaine individuelle ? ou qu'il faut une page "région" qui présente les domaines d'une région en plus de la page "domaine" qui présente un seul domaine ?

**Comment by Shuunen** [comment]
en gros il faut penser navigation, qu'est ce qu'on propose à l'utilisateur ?

@bengrol , @LeGaby  venez sur https://github.com/Shuunen/bergerac-roads/issues/17
