### ISSUE TITLE
Script API

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#14]
Créer un script qui interroge l'API Sirtaki et format le résultat.

**Comment by bengrol** [comment]
Il faudrait faire un essai d’utilisation du retour du json de l’API sirtaki (info dans le projet)
Si c’est inutilisable, réfléchir à un système en back avec Léo pour les appels et modifications des donnés.

**Comment by Shuunen** [comment]
Je vais voir pour intégrer ça au build continu comme ça on aurait des données fraiches à chaque déploiement

**Comment by Shuunen** [comment]
@bengrol je vois pas où récupérer les variables dans : 
`http://{{syndic_url_opt}}/{{syndic_name}}/{{syndic_key}}/Objects?$format=json&$top=10`

**Comment by Shuunen** [comment]
Les copier ok mais où ?

**Comment by Shuunen** [comment]
Par exemple syndic_url_opt c'est dans quel fichier ?

**Comment by bengrol** [comment]
Le fichier s’app Postman_config (a la racine du projet) et tu le copie dans
postman.
Tu crée un environnement - roue crantée en haut à droite -> manage
environnement - add - bulk edit et tu copies le contenu.
Ensuite, tu sélectionnes l’env que tu viens de créer.



Le mar. 29 mai 2018 à 10:30, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
Ha yes ça marche :+1:  merci

**Comment by Shuunen** [comment]
c'est bon de mon côté oui

**Comment by bengrol** [comment]
Tu veux dire que tu peux l’utiliser ?????????
Si c’est ça c’est bien cool !!!
