### ISSUE TITLE
infobulle map

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#22]

**Comment by LeGaby** [comment]
@bengrol je viens de commit sur master la fonctionnalité de (dé)sélection des domaines via l'infobulle. Si tu peux tester en détails et me donner ton avis, ce serait top !

**Comment by bengrol** [comment]
l'ajout fonctionne à partir de l'info bulle.
En revanche il n'est plus possible de créer le trajet. C'est en cours peut-être (?)

**Comment by LeGaby** [comment]
Non, c'est toujours possible. C'est le bouton en forme d'oeil à côté du champ d'adresse. Apparemment, ce n'est pas intuitif, je vais changer le bouton du coup.

**Comment by bengrol** [comment]
Oui j’ai essayé mais il ne s’est rien passé

**Comment by LeGaby** [comment]
En effet, ça ne marche pas toujours, je regarderai.

**Comment by LeGaby** [comment]
@bengrol je n'arrive finalement pas à reproduire, tu as un exemple précis ?

**Comment by bengrol** [comment]
Nous avons eut une coupure de réseau hier. J’ai dû tester pendant. Moi non je ne reproduis pas.

**Comment by bengrol** [comment]
Les autres POI restent après avoir tracé l’itinéraire - c’est possible de les enlever ?

**Comment by LeGaby** [comment]
Normalement, c'est possible oui. Sinon, j'ai réussi à reproduire ce dont on parlait avant. C'est quand Google Maps ne trouve pas les points sélectionnés à partir de leur nom donc je vais faire avec leurs coordonnées.

**Comment by bengrol** [comment]
ok - good

**Comment by LeGaby** [comment]
@bengrol J'ai réfléchi sur le sujet de la disparition des marqueurs après création de l'itinéraire et je ne trouve pas cela très optimisé car dans ce cas, quand est-ce que les marqueurs reviennent ? Si on les fait revenir àprès une nouvelle recherche, cela veut dire que pour faire un nouvel itinéraire avec l'ancienne recherche, on peut les sélectionner dans la liste sans les voir sur la carte. Etc. Selon moi, ça rajoute pas mal de complexité niveau interactions et niveau code. Vois-tu ce dont je parle ?

**Comment by LeGaby** [comment]
Dernière fonctionnalité évoquée dans #42. Infobulles mises en place.
