### ISSUE TITLE
partager l’itinéraire par mail (4h)

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#24]

**Comment by bengrol** [comment]
Il doit être possible pour l'utilisateur de partager son itinéraire par mail, et sur les réseau sociaux.

**Comment by bengrol** [comment]
Il faut aussi qu'il puisse l'imprimer avec les info importantes : adresse contact horaires des domaines

**Comment by Shuunen** [comment]
@bengrol critique ou amélioration ?

**Comment by bengrol** [comment]
Amélioration

Le jeu. 23 août 2018 à 12:13, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
@bengrol sachant que c'est lié au dev des itinéraires built-in ?

**Comment by Shuunen** [comment]
fixed by #175
