### ISSUE TITLE
Import/utilité des tags

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#25]
J'importe actuellement ces tags qui je pense seront utilisés : 
- ACCESHANDI (accès handicapé)
- AGRIRAISONNE (agriculture raisonnée)
- VENTEPROPRIETE (vente de vins sur place je suppose ?)
- ANIMAUX (animaux acceptés je suppose ?)
- AGRIBIODYN (agriculture biodynamique)
- AGRIBIO (agriculture bio)

Et pas ceux ci car soit je ne vois pas leur utilité : 
- GROUPEAUTOCAR
- GROUPE

Voici mes questions @bengrol  : 
- est-ce que les tags importés couvrent tous les cas de recherche ?
- s'il en manque les-quels ?
- mes interprétations sur le sens des tags sont-elles correctes ?
- qu'est ce que GROUPE et GROUPEAUTOCAR ?
- il y a t'il d'autres tags à prendre en compte dans l'api qui ne sont pas des clés avec comme valeur "oui" / "non" ? par exemple est-ce que `"HANDICAPLABEL": null,` sous-entends `"HANDICAPLABEL": false,` ?

**Comment by bengrol** [comment]
@Shuunen Je suis Ok avec ces filtres. 

> est-ce que les tags importés couvrent tous les cas de recherche ?
Je pense que oui

> mes interprétations sur le sens des tags sont-elles correctes ?
Ces sont les mêmes que moi en tous cas.

Je pense que "GROUPE" c'est les visites en groupes alors que "GROUPEAUTOCAR" c'est les groupes venant en BUS (donc avec une aire de stationnement)

Donc, ON PART LA DESSUS !!!!

**Comment by Shuunen** [comment]
du coup les tags c'est good
