### ISSUE TITLE
Optimize cdn

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#27]
Here is the headers from Netlify serving a jpg : 

Request URL: https://bergerac-roads.netlify.com/images/entrant/credit-photo-Akim-Benbrahim.jpg
Request Method: GET
Status Code: 200  (from ServiceWorker)
Remote Address: 54.229.14.125:443
Referrer Policy: no-referrer-when-downgrade
accept-ranges: bytes
age: 9
cache-control: public,max-age=31536000
content-length: 247368
content-type: image/jpeg
date: Thu, 14 Jun 2018 18:42:44 GMT
etag: "091b681286a44c02cac16b879744520b-ssl"
server: Netlify
status: 200

And here is what OVH default server send : 

Request URL: http://bergerac.lebowsky-dev.xyz/images/entrant/credit-photo-Akim-Benbrahim.jpg
Request Method: GET
Status Code: 200 OK
Remote Address: 213.186.33.18:80
Referrer Policy: no-referrer-when-downgrade
Accept-Ranges: bytes
Cache-Control: max-age=900
Content-Length: 247368
Content-Type: image/jpeg
Date: Thu, 14 Jun 2018 18:45:00 GMT
Expires: Thu, 14 Jun 2018 19:00:00 GMT
Last-Modified: Thu, 14 Jun 2018 18:03:48 GMT
Server: Apache
X-IPLB-Instance: 17325

OVH max age is 15 minures while Netlify max ages is 365 days

**Comment by bengrol** [comment]
@Shuunen  Quelle est la durée que tu proposes ?

**Comment by Shuunen** [comment]
1 an c'est très bien

**Comment by bengrol** [comment]
je m'en occupe
