### ISSUE TITLE
CRON sur serveur (?? h)

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#28]
Créer un script + tache CRON sur serveur.
créer script de MAJ + tache CRON

**Comment by Shuunen** [comment]
faire un script tout simple pour tester

**Comment by Shuunen** [comment]
@bengrol j'ai pas accès au cron via mon accès SSH (`crontab -e`)

voilà ce que tu peux tester pour le moment : 

`*/30 * * * * echo "cron executed at $(TZ=":Europe/Paris" date +%F_%H-%M-%S)" >> ~/cron.log`

ça loggera les exécutions du cron dans `~/cron.log`, toutes les 30 minutes 😃 

si ça marche pas, il me faudrait ces infos : 

- quelle formule tu as chez OVH ?
- quelle distrib linux ? si c'est la même que mon accès SSH je vois Debian 6
- si tu ne retrouve pas `~/cron.log`, tu as un dossier `/home/ton-user` où je pourrais écrire ces logs ?

**Comment by Shuunen** [comment]
@bengrol du nouveau à ce sujet ?

**Comment by Shuunen** [comment]
mais le build ne met pas à jour la base actuellement, je fais la modif...

**Comment by Shuunen** [comment]
@bengrol  : désormais chaque build MAJ la BDD

**Comment by bengrol** [comment]
PARFAIT !!!!!!
