### ISSUE TITLE
placement des photos (3h)

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#30]
Je sais qu'il éxiste des lib pour détecter les visages afin de bien placer les photos

Parce que dans ce genre de cas c'est bof :  

![image](https://user-images.githubusercontent.com/439158/41682161-38b49d6c-74d7-11e8-971a-6c007fadd274.png)

Z'en pensez quoi ?

**Comment by bengrol** [comment]
Pourquoi pas quand l’appli sera livrée.


Le mer. 20 juin 2018 à 22:14, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
duplicate of #46
