### ISSUE TITLE
itinéraires built-in (2h)

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#35]
Il faudrait des itinéraires pré-conçus, accessible via les 3 vignettes du bas (qui remplacerait les liens sous "Domaines ajoutés récemment") avec des thématiques du genre : 

- « Ma route des vins avec des enfants » 
- « Ma route des vins bio » 
- « le TOP10 de la route des vins »

**Comment by bengrol** [comment]
Des paramètres dans l'url me semble la solution la plus simple/rapide - @Shuunen ?

**Comment by Shuunen** [comment]
faire un système /itinéraires/12+35+65
reconstituer les ids : DEGAQU0 + 12
et générer l'iténéraire à la volée

ensuite ajouter des redirs du genre  /itinéraires/top-10 =>  /itinéraires/12+35+65

**Comment by Shuunen** [comment]
fait suite à #24
