### ISSUE TITLE
bloqué sur mobile suite au scroll sur la carte

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#38]
![image](https://user-images.githubusercontent.com/439158/41740211-9cfed63c-7597-11e8-9669-f1cd24aa4cd6.png)

pour reproduire : mettre un filtre lancer la recherche scroller vers la carte, là on est coincé on peut plus rien faire

bug sur mon tel Moto G4 Plus sous Chrome

**Comment by Shuunen** [comment]
freeze reproduit sur chrome desktop

**Comment by LeGaby** [comment]
Reproduit sur Firefox sur mon smartphone. J'ai de plus eu une alerte "Unresponsive script : maps.googleapis.com etc. Do you want to stop the script or continue ?" Ce serait l'API Google Maps qui déconne ? Ça m'étonne.
