### ISSUE TITLE
remonter les domaines sélectionnés

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#41]
je pense que ça vaudrait le coup de mettre en haut de liste les domaines sélectionnés

![image](https://user-images.githubusercontent.com/439158/41909526-84b4f4f4-7947-11e8-97a0-b9b97d7acbd5.png)

là j'en ai pris 3 sur la carte et le panneau de gauche n'a pas réagi, ce serait cool de voir un feedback à gauche quand on change à droite, et inversement, sachant que les deux sont liés, il faudrait que cette liaison soit visuelle aussi

**Comment by bengrol** [comment]
Il faudrait également mettre le nb de domaine affiché

**Comment by bengrol** [comment]
Sur mobile la fonction « me localiser » ne fonctionne pas
