### ISSUE TITLE
actualiser l'itinéraire au choix d'une nouvelle destination

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#43]
je viens de choisir de passer aussi au "Château Haut Lamouthe" mais l'itinéraire n'a pas changé

![image](https://user-images.githubusercontent.com/439158/41909772-2bbc72e0-7948-11e8-8759-3f92cfe0d4f4.png)

**Comment by LeGaby** [comment]
Il faut rappuyer sur le bouton "Itinéraire" pour lancer la recherche et l'affichage d'un nouvel itinéraire.

**Comment by Shuunen** [comment]
fixé
