### ISSUE TITLE
ajouter des infos aux vignettes de domaine

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#44]
comme dans le pdf 

![image](https://user-images.githubusercontent.com/439158/42159885-a01a9c96-7df5-11e8-8410-77516f3d0fd2.png)

**Comment by Shuunen** [comment]
![image](https://user-images.githubusercontent.com/439158/42159914-bc1542c0-7df5-11e8-8a17-9f331706df99.png)

**Comment by Shuunen** [comment]
voilà à quoi ressemble les domaines désormais : 

![image](https://user-images.githubusercontent.com/439158/42411523-8671860e-81fd-11e8-8e79-20ff7eeb12f9.png)

suffisant pour cloturer cette tâche @bengrol ? ou il faut ajouter d'autres infos ?

**Comment by bengrol** [comment]
non c'est good
