### ISSUE TITLE
ajouter des infos sur la page domaine (1h)

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/bergerac-roads#45]
pour l'instant on a du lorem ipsum 🥇

**Comment by bengrol** [comment]
Maintenant qu'on a les infos, il faudrait la designer un peu, et la responsiviser (ouais ça existe pas ) - tu peux estimer le temps ?

**Comment by Shuunen** [comment]
@bengrol  l'estimation est déjà dans le titre non ?

**Comment by Shuunen** [comment]
fixed
