### ISSUE TITLE
modifer google API key

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#47]
modifer google api key 
ici plugins/google-maps.js

**Comment by Shuunen** [comment]
@bengrol le soucis c'est que les iténéraires sont payants désormais : 

https://mapsplatformtransition.withgoogle.com/calculator

**Comment by bengrol** [comment]
je vais demander au client qu'il créé une clé.
Mais a priori, en dessous de 30 000 appel c''est gratuit.

**Comment by bengrol** [comment]
Du coup, comment on pourrait faire pour que cette clé ne soit pas sur le repo publique ?

**Comment by bengrol** [comment]
ok

Le mer. 22 août 2018 à 15:42, Romain Racamier <notifications@github.com> a
écrit :

> La clé sera sur le repo public et dans les sources compilées de toute
> manière,
>
> Mais les API Google sont protégés par les restrictions appliquées aux clés,
> par exemple la restriction par domaine rendra obsolète la clé sur d'autres
> domaines que bergerac-roads.netlify.com
>
>

**Comment by bengrol** [comment]
C'est bon, je l'ai ajouté
