### ISSUE TITLE
modification listing domaine (2h)

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#50]
Changer l'affichage du listing des domaines, actuellement sous forme de case à cocher, en une pastille (idem à celle déjà présente en dessous)
![pastille listing](https://user-images.githubusercontent.com/3702150/44514351-2638fa00-a6c0-11e8-95fe-6605821b9146.png)

Dans cette pastille, ajouter un lien (_blank) vers la page du domaine en question

**Comment by bengrol** [comment]
Il faudrait également que le bouton "Calculer mon itinéraire" apparaisse à coté de la phrase "Vous avez sélectionné x domaine " plutôt qu'en bas de page.

**Comment by Shuunen** [comment]
@bengrol ?

**Comment by bengrol** [comment]
Oui - en adaptant la taille.

**Comment by Shuunen** [comment]
@bengrol comme ceci (https://bergerac-roads.netlify.com/) ?
