### ISSUE TITLE
ajouter un champ de filtrage des domaines (1h)

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#51]
ajouter une barre de recherche juste en dessous de la barre de localisation.
Ce champ ne ferait que filtrer les domaines afficher en dessous (filtre sur les nom et lieux)

**Comment by bengrol** [comment]
1h => Parfait

**Comment by Shuunen** [comment]
du coup j'étais sur cette tâche #51 au moment où tu m'a dis que la #8 n'était pas bien implémentée, je push pour que tu vois l'implémentation actuelle avec : 
- filtre checkbox pour les vignobles 
- filtre texte pour les domaines

**Comment by Shuunen** [comment]
@bengrol : tu peux voir sur https://bergerac-roads.netlify.com/

**Comment by bengrol** [comment]
OUI ! Nickel.

Le jeu. 30 août 2018 à 12:58, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
du coup on reste là dessus ?

**Comment by bengrol** [comment]
OUI

Le jeu. 30 août 2018 à 13:06, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
![image](https://user-images.githubusercontent.com/439158/44848288-75e66b00-ac56-11e8-9d68-12fa00837478.png)

**Comment by bengrol** [comment]
LoOooLOoOOoooOL


Le jeu. 30 août 2018 à 13:13, Romain Racamier <notifications@github.com> a
écrit :
