### ISSUE TITLE
ajouter le filtrage par région et vignobles (2h)

### ISSUE THREAD

**Issue by bengrol** [Shuunen/bergerac-roads#8]
inclure google map
tracer un chemin static ( en Dordogne )

**Comment by bengrol** [comment]
@LeGaby Comme on s'est dit, tu peux commencer par créer une page, et utiliser un jeux de données bouchonné. On l'intégrera plus tard à la page de résultat de recherche.

**Comment by LeGaby** [comment]
Salut Ben. Je devais te tenir au courant hier, j'ai fait une nouvelle page
avec une carte Google Maps dessus (branche fracture/map). Très instinctifs
ces Nuxt.js et Vue.js, aucun souci. Je me mets aujourd'hui à créer le jeu
de données bouchon, à placer les marqueurs et à tenter de faire des
itinéraires.

**Comment by bengrol** [comment]
@LeGaby je pense qu'il faudrait pouvoir rentrer manuellement l'adresse. Pour ceux qui veulent prévoir un trip à partir d'un endroit définit.

**Comment by Shuunen** [comment]
@LeGaby si ça peut aider : https://www.grafikart.fr/tutoriels/javascript/google-maps-marker-personnalise-1005

**Comment by bengrol** [comment]
@LeGaby Pourrais tu centrer la map sur Bergerac avec un zoom assez proche stp.

**Comment by bengrol** [comment]
Suite au point avec le client, quelques points sont à modifier :
la carte doit être affiché directement au chargement. (donc non-filtrée)
Les tags, doivent être ceux présent sur le guide pdf, à savoir : 
- vignobles & découvertes
- Bienvenue à la Ferme
- Agriculture Biologique
- Tourisme & Handicap
- Vignerons Indépendant
- Haute Valeur Environnementale
- AOC
- Terra Vitis
- France Passion
- Accessibilité
- Camping-cars
- Hébergement
- Restauration
- Familles
- Monument.
- + les 10 domaines viticoles 

Réfléchir à utiliser les pictos plutôt qu'un mutli select
voir pj
![screenshot from 2018-06-25 18-06-44](https://user-images.githubusercontent.com/3702150/41861837-a0dc02c6-78a2-11e8-8cd9-8aba2df5a444.png)

**Comment by Shuunen** [comment]
@bengrol  en effet utiliser des pictos ce serait plus intuitif, mais vu la dose de tag ci-dessus... je vois pas comment rendre ça clair...

**Comment by Shuunen** [comment]
Quelque chose du genre serait plus pratique à mon gout : 

![image](https://user-images.githubusercontent.com/439158/41912417-fd473c1c-794f-11e8-9e4f-7f452c3dc72f.png)

Maquette dispo sur le drive : https://drive.google.com/open?id=1xN6r1_PBCDa6TnmxhD9xxTDBZA-ccWCv

**Comment by LeGaby** [comment]
Si vous voulez des pictos, pourquoi ne pas juste les rajouter dans le multiselect ?
https://vue-multiselect.js.org/#sub-custom-option-template

**Comment by Shuunen** [comment]
> Si vous voulez des pictos

Je tiens à préciser que pour ma part c'est plus une suggestion qu'une envie, je trouve que le multiselect n'est pas user-friendly, mais au final ce n'est que mon point de vue et c'est @bengrol qui doit valider avec la cliente les besoins et les solutions à mettre en oeuvre

**Comment by LeGaby** [comment]
@Shuunen, j'avais bien compris que ce n'était pas une envie de ta part, et je suis d'accord avec toi, surtout pour la partie mobile.

**Comment by bengrol** [comment]
@Shuunen ta proposition de picto est bien. Je pense qu’il faut se diriger vers ça

**Comment by Shuunen** [comment]
j'ai essayé de faire un combo entre options de filtrage les plus utilisées et en dessous pour les experts de la recherche viticole qui veulent que du "Terra Vitis"

**Comment by Shuunen** [comment]
@bengrol 3 questions pour toi : 
1) Le tag "vignobles & découvertes" ça filtre sur quel critère ? 
2) Différence entre "Tourisme & Handicap" et "Accessibilité" pour une personne à mobilité réduite ?
3) Elle en pense quoi la dame de cette recherche à coucher dehors ?

**Comment by bengrol** [comment]
1&2) je ne sais pas - je n’ai pas eu le temps de regarder l’api 
3) je vois ce que tu veux dire. N’étant pas client de ce genre d’appli, j’ai du mal à me projeter en tant qu’utilisateur - pour tt dire je ne comprends même pas l’intitulé des tags

**Comment by Shuunen** [comment]
@bengrol voici le nouveau rendu : 

![image](https://user-images.githubusercontent.com/439158/42846651-e3a204b0-8a19-11e8-92b3-ec9563238c3e.png)

reste à ajouter un lien "Filtrer par région et vignobles" qui affichera des checkbox pour filtrer par vignobles

**Comment by bengrol** [comment]
heuuuuuuu, je voyais plus un truc comme ça :
https://codepen.io/bengrol/pen/XPNzRW

Le jeu. 30 août 2018 à 11:35, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
bah ça aurait été cool d'avoir cet exemple avant que je passe du temps dessus 😠 

surtout que ci-dessus l'issue est clairement : 

> ![image](https://user-images.githubusercontent.com/439158/44847189-e7bcb580-ac52-11e8-9f89-cfbc6c499325.png)

**Comment by bengrol** [comment]
Je pensais que l’explication était bonne.
J’ai fait le code pen ce matin en constatant que je m’etais mal exprimé.
Mais c’est pas grave, le filtrage que tu as fait est bien, il faut le
garder.

Le jeu. 30 août 2018 à 12:48, Romain Racamier <notifications@github.com> a
écrit :

**Comment by Shuunen** [comment]
si c'est du filtrage texte (et non checkbox pour filtrer par vignobles) de domaines qu'on parle alors laissons cette issue fermée et allons sur celle que t'as ouverte la #51 qui correspond à ce que tu voulais
